PyPowerDNS/__init__.py,sha256=47DEQpj8HBSa-_TImW-5JCeuQeRkm5NMpJWZG3hSuFU,0
PyPowerDNS/api.py,sha256=Yq9g5mOX9pCnYGgGCPhp6xUEXwYroo8NJmN9XkkRpt8,8669
PyPowerDNS/exceptions.py,sha256=rWPWpnOfFaZ7-2Bjir91b94SwnLoLDfft2eTFW2qMJ4,411
PyPowerDNS/objects.py,sha256=q_U-HjB9Vn8SQY2z0KDqGDdZWp8ub7znM7iqj5EnqyU,4584
PyPowerDNS-2022.4.1.dist-info/LICENSE,sha256=o-MOeR1ubHEdYt1VtnuVgEkvPELmtVghhH_jcpyOD_k,1072
PyPowerDNS-2022.4.1.dist-info/METADATA,sha256=jrgrKjU0GeMNSKvMx8WWHctOOnPAlN2Q4uxFFun_Y4k,1278
PyPowerDNS-2022.4.1.dist-info/WHEEL,sha256=G16H4A3IeoQmnOrYV4ueZGKSjhipXx8zc8nu9FGlvMA,92
PyPowerDNS-2022.4.1.dist-info/top_level.txt,sha256=WfWlEFbu5uoB3-H8b99NmqxfSD5eDw-6ivtItplm2PU,11
PyPowerDNS-2022.4.1.dist-info/RECORD,,
